### ISSUE TITLE
[Request] Support Foundry projects out of the box

### ISSUE THREAD

**Issue by jmhickman** [Ackee-Blockchain/tools-for-solidity-vscode#37]
It seems like hardhat projects work out of the box, where the addon doesn't seem to have an issue tracking down dependencies. 

As Foundry is getting more popular, at least for the work I do, it would be nice to have equal support for Foundry, so that I don't have to do a lot of manual steps to get imports to resolve.

**Comment by michprev** [comment]
I am not very happy with the way Foundry chose to resolve "external" imports - remappings. Remappings can get complicated or even counterintuitive in some cases. With other projects (external dependencies stored in the `node_modules` directory), the situation is easier. We can just add `node_modules` to the `include_paths` config (i.e., paths where to search for non-relative imports) - the rest of the import path reflects the actual path in the filesystem, and everything works fine. This is not the case for Foundry remappings, where imports do not reflect the path in the filesystem. Because Foundry remappings are specific for every project, we cannot include a simple default config option to make it work out of the box. Still, we would like to include at least some support for Foundry.

To make imports in Foundry projects work:
- we should overwrite VS Code workspace settings of `woke.compiler.solc.remappings` with the output of `forge remappings`
    - we don't want to overwrite users' settings without their knowledge
    - instead, we would like to implement VS Code command "Import Foundry Remappings" that can be manually executed by a user
- I had a chance to work with a Foundry project where `forge remappings` does not print all the remappings needed (the project does not compile with this remappings) - we can do nothing about that
- we will have to guess the location of the `forge` binary - it is not stored under a common path like `/usr/bin`
- as a fallback, we can try to read `remappings.txt` file in the workspace root directory
    - however, the file name does not seem to be standardized and the file does not seem to be included in every Foundry project

**Comment by jmhickman** [comment]
Yeah, I understand. What I've done in the interim is used a combination of the `woke.compiler.solc.remappings` and symlinks in the filesystem to deal with projects developed in `hardhat` and thus using the `@` notation for imports.

![image](https://user-images.githubusercontent.com/6581761/211607430-b3059efa-e99a-4e6a-ad45-e7038a102400.png)
![image](https://user-images.githubusercontent.com/6581761/211607630-d45d6f94-1759-4314-b246-e9d1ed401612.png)

I think manually importing remappings from foundry.toml into the `woke.compiler.solc.remappings` and letting the user address any lingering missing imports is the best bet. This way, you don't have to worry about the location of `forge` and the user will get the preponderance of the imports, enough that the leftovers won't be that bad.

**Comment by michprev** [comment]
Turned out to be easier to guess the location of the `forge` binary than parsing `foundry.toml`. I think we would have to process all `foundry.toml` files recursively in subdirectories. As a fallback, we try to read `remappings.txt` in the workspace root. The command `Tools for Solidity: Import Foundry Remappings` is available in version 1.4.0 (released just now, should be available soon on the marketplace).

**Comment by jmhickman** [comment]
Just wanted to say that I had the chance to try this just now, and it worked perfectly. Thanks again for adding it!

**Comment by llllvvuu** [comment]
Could another approach be to have a CLI flag for the LSP that tells it to dynamically import Foundry remappings on initialization, rather than having a separate command to update a static config?
